name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: macos-latest
    steps:
      - name: Output Github context
        run: echo "GITHUB_CONTEXT: ${{ toJSON(github) }}"

      - name: Output information
        run: echo "Information has been outputted successfully!"
